
esphome:
  name: 00-smart-meter-sml
  friendly_name: 00_smart_meter_SML

esp8266:
  board: d1_mini

# Enable logging
logger:
  level: DEBUG
    # for initial setup: VERY_VERBOSE
  logs:
    sml: DEBUG
    text_sensor: DEBUG
# Enable Home Assistant API
api:
  encryption:
    key: "YOUR KEY"
# Please Use the Key which ESP Home automatically provided
# bitte nutzt den Key, der nach der Erstellung der ESP Home Instanz bei euch von Home Assistant eingetragen worden ist. 


ota:
  password: "yourOTAPW"
# Please Use the OTA PWD which ESP Home automatically provided
# bitte nutzt den OTA PWD, der nach der Erstellung der ESP Home Instanz bei euch von Home Assistant eingetragen worden ist. 

wifi:
  ssid: "secret wifi_ssid"
  password: "secret wifi_password"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "00-Smart-Meter-Sml"
    password: "9845hkksdfkhjshjdg"


captive_portal:


uart:
  id: uart_bus
  rx_pin: 
  #D7 GPIO13 bei Wemos D1 Mini, other boars may use different Pin Layouts. 
    number: D7
    inverted: false
  baud_rate: 9600
  data_bits: 8
  parity: NONE
  stop_bits: 1
  debug: 

sml:
  id: mysml
  uart_id: uart_bus


text_sensor:
  - platform: sml
    name: "ED100l"
    #Change to your Smart Meter Name
    sml_id: mysml
    server_id: "YOURSERVERID"
    #Change to your server ID as visiable fro the text debug console
    obis_code: "129-129:199.130.3"
    format: text
sensor:
  - platform: sml
    name: "SM_Total energy bought"
    sml_id: mysml
    obis_code: "1-0:1.8.0"
    unit_of_measurement: kWh
    accuracy_decimals: 4
    device_class: energy
    state_class: total_increasing
    filters:
      - multiply: 0.0001
  - platform: sml
    name: "SM_Total energy bought-1.8.2"
    sml_id: mysml
    obis_code: "1-0:1.8.2"
    unit_of_measurement: kWh
    accuracy_decimals: 4
    device_class: energy
    state_class: total_increasing
    filters:
      - multiply: 0.0001
  - platform: sml
    name: "SM_Total energy sold"
    sml_id: mysml
    obis_code: "1-0:2.8.0"
    unit_of_measurement: kWh
    accuracy_decimals: 4
    device_class: energy
    state_class: total_increasing
    filters:
      - multiply: 0.0001

  - platform: sml
    name: "Current load"
    sml_id: mysml
    obis_code: "1-0:16.7.0"
    unit_of_measurement: W
    accuracy_decimals: 0
    device_class: energy
    filters:
      - multiply: 0.1
